behaviors:
  TetrisAgent:
    trainer_type: ppo
    max_steps: 500000
    time_horizon: 128
    summary_freq: 10000
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 3.0e-4
    network_settings:
      num_layers: 2
      hidden_units: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
